version: '3'

services:
  flask_app:
    container_name: emotional-analysis
    restart: always
    build: ./flaskapp
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b :8000 app:app

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - flaskapp
